# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.16.3 is version 34
loaderVersion="[34,)"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false
#lisence
license="All Rights Reserved"

[[mods]]
modId="juicesandsodas"
version="1.0.0.0"
displayName="Juices & Sodas"
updateJSONURL=""
displayURL="screret.github.io"
logoFile= "pack.png"
credits=""
authors="screret"
description='''
      adds some popular (and ...less popular) juices and sodas!'''

[[dependencies.juicesandsodas]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"

[[dependencies.juicesandsodas]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"